// Code generated by protoc-gen-go. DO NOT EDIT.
// source: helloworld/helloworld/helloworld.proto

package helloworld

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec74e253189a04b7, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec74e253189a04b7, []int{1}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ProfessorRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Subject              string   `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfessorRequest) Reset()         { *m = ProfessorRequest{} }
func (m *ProfessorRequest) String() string { return proto.CompactTextString(m) }
func (*ProfessorRequest) ProtoMessage()    {}
func (*ProfessorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec74e253189a04b7, []int{2}
}

func (m *ProfessorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfessorRequest.Unmarshal(m, b)
}
func (m *ProfessorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfessorRequest.Marshal(b, m, deterministic)
}
func (m *ProfessorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfessorRequest.Merge(m, src)
}
func (m *ProfessorRequest) XXX_Size() int {
	return xxx_messageInfo_ProfessorRequest.Size(m)
}
func (m *ProfessorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfessorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProfessorRequest proto.InternalMessageInfo

func (m *ProfessorRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProfessorRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *ProfessorRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ProfessorReply struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Subject              string   `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfessorReply) Reset()         { *m = ProfessorReply{} }
func (m *ProfessorReply) String() string { return proto.CompactTextString(m) }
func (*ProfessorReply) ProtoMessage()    {}
func (*ProfessorReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec74e253189a04b7, []int{3}
}

func (m *ProfessorReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfessorReply.Unmarshal(m, b)
}
func (m *ProfessorReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfessorReply.Marshal(b, m, deterministic)
}
func (m *ProfessorReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfessorReply.Merge(m, src)
}
func (m *ProfessorReply) XXX_Size() int {
	return xxx_messageInfo_ProfessorReply.Size(m)
}
func (m *ProfessorReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfessorReply.DiscardUnknown(m)
}

var xxx_messageInfo_ProfessorReply proto.InternalMessageInfo

func (m *ProfessorReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProfessorReply) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *ProfessorReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CourseRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CourseRequest) Reset()         { *m = CourseRequest{} }
func (m *CourseRequest) String() string { return proto.CompactTextString(m) }
func (*CourseRequest) ProtoMessage()    {}
func (*CourseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec74e253189a04b7, []int{4}
}

func (m *CourseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourseRequest.Unmarshal(m, b)
}
func (m *CourseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourseRequest.Marshal(b, m, deterministic)
}
func (m *CourseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourseRequest.Merge(m, src)
}
func (m *CourseRequest) XXX_Size() int {
	return xxx_messageInfo_CourseRequest.Size(m)
}
func (m *CourseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CourseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CourseRequest proto.InternalMessageInfo

func (m *CourseRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CourseRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CourseReply struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CourseReply) Reset()         { *m = CourseReply{} }
func (m *CourseReply) String() string { return proto.CompactTextString(m) }
func (*CourseReply) ProtoMessage()    {}
func (*CourseReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec74e253189a04b7, []int{5}
}

func (m *CourseReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourseReply.Unmarshal(m, b)
}
func (m *CourseReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourseReply.Marshal(b, m, deterministic)
}
func (m *CourseReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourseReply.Merge(m, src)
}
func (m *CourseReply) XXX_Size() int {
	return xxx_messageInfo_CourseReply.Size(m)
}
func (m *CourseReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CourseReply.DiscardUnknown(m)
}

var xxx_messageInfo_CourseReply proto.InternalMessageInfo

func (m *CourseReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CourseReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type StudentRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StudentRequest) Reset()         { *m = StudentRequest{} }
func (m *StudentRequest) String() string { return proto.CompactTextString(m) }
func (*StudentRequest) ProtoMessage()    {}
func (*StudentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec74e253189a04b7, []int{6}
}

func (m *StudentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StudentRequest.Unmarshal(m, b)
}
func (m *StudentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StudentRequest.Marshal(b, m, deterministic)
}
func (m *StudentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StudentRequest.Merge(m, src)
}
func (m *StudentRequest) XXX_Size() int {
	return xxx_messageInfo_StudentRequest.Size(m)
}
func (m *StudentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StudentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StudentRequest proto.InternalMessageInfo

func (m *StudentRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StudentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type StudentReply struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StudentReply) Reset()         { *m = StudentReply{} }
func (m *StudentReply) String() string { return proto.CompactTextString(m) }
func (*StudentReply) ProtoMessage()    {}
func (*StudentReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec74e253189a04b7, []int{7}
}

func (m *StudentReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StudentReply.Unmarshal(m, b)
}
func (m *StudentReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StudentReply.Marshal(b, m, deterministic)
}
func (m *StudentReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StudentReply.Merge(m, src)
}
func (m *StudentReply) XXX_Size() int {
	return xxx_messageInfo_StudentReply.Size(m)
}
func (m *StudentReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StudentReply.DiscardUnknown(m)
}

var xxx_messageInfo_StudentReply proto.InternalMessageInfo

func (m *StudentReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StudentReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type StudentCourseRequest struct {
	StudentName          string   `protobuf:"bytes,1,opt,name=studentName,proto3" json:"studentName,omitempty"`
	CourseName           string   `protobuf:"bytes,2,opt,name=courseName,proto3" json:"courseName,omitempty"`
	ProfessorName        string   `protobuf:"bytes,3,opt,name=professorName,proto3" json:"professorName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StudentCourseRequest) Reset()         { *m = StudentCourseRequest{} }
func (m *StudentCourseRequest) String() string { return proto.CompactTextString(m) }
func (*StudentCourseRequest) ProtoMessage()    {}
func (*StudentCourseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec74e253189a04b7, []int{8}
}

func (m *StudentCourseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StudentCourseRequest.Unmarshal(m, b)
}
func (m *StudentCourseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StudentCourseRequest.Marshal(b, m, deterministic)
}
func (m *StudentCourseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StudentCourseRequest.Merge(m, src)
}
func (m *StudentCourseRequest) XXX_Size() int {
	return xxx_messageInfo_StudentCourseRequest.Size(m)
}
func (m *StudentCourseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StudentCourseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StudentCourseRequest proto.InternalMessageInfo

func (m *StudentCourseRequest) GetStudentName() string {
	if m != nil {
		return m.StudentName
	}
	return ""
}

func (m *StudentCourseRequest) GetCourseName() string {
	if m != nil {
		return m.CourseName
	}
	return ""
}

func (m *StudentCourseRequest) GetProfessorName() string {
	if m != nil {
		return m.ProfessorName
	}
	return ""
}

type StudentCourseReply struct {
	StudentName          string   `protobuf:"bytes,1,opt,name=studentName,proto3" json:"studentName,omitempty"`
	CourseName           string   `protobuf:"bytes,2,opt,name=courseName,proto3" json:"courseName,omitempty"`
	ProfessorName        string   `protobuf:"bytes,3,opt,name=professorName,proto3" json:"professorName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StudentCourseReply) Reset()         { *m = StudentCourseReply{} }
func (m *StudentCourseReply) String() string { return proto.CompactTextString(m) }
func (*StudentCourseReply) ProtoMessage()    {}
func (*StudentCourseReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec74e253189a04b7, []int{9}
}

func (m *StudentCourseReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StudentCourseReply.Unmarshal(m, b)
}
func (m *StudentCourseReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StudentCourseReply.Marshal(b, m, deterministic)
}
func (m *StudentCourseReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StudentCourseReply.Merge(m, src)
}
func (m *StudentCourseReply) XXX_Size() int {
	return xxx_messageInfo_StudentCourseReply.Size(m)
}
func (m *StudentCourseReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StudentCourseReply.DiscardUnknown(m)
}

var xxx_messageInfo_StudentCourseReply proto.InternalMessageInfo

func (m *StudentCourseReply) GetStudentName() string {
	if m != nil {
		return m.StudentName
	}
	return ""
}

func (m *StudentCourseReply) GetCourseName() string {
	if m != nil {
		return m.CourseName
	}
	return ""
}

func (m *StudentCourseReply) GetProfessorName() string {
	if m != nil {
		return m.ProfessorName
	}
	return ""
}

type StudentCourseSearchRequest struct {
	StudentName          string   `protobuf:"bytes,1,opt,name=studentName,proto3" json:"studentName,omitempty"`
	CourseName           string   `protobuf:"bytes,2,opt,name=courseName,proto3" json:"courseName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StudentCourseSearchRequest) Reset()         { *m = StudentCourseSearchRequest{} }
func (m *StudentCourseSearchRequest) String() string { return proto.CompactTextString(m) }
func (*StudentCourseSearchRequest) ProtoMessage()    {}
func (*StudentCourseSearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec74e253189a04b7, []int{10}
}

func (m *StudentCourseSearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StudentCourseSearchRequest.Unmarshal(m, b)
}
func (m *StudentCourseSearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StudentCourseSearchRequest.Marshal(b, m, deterministic)
}
func (m *StudentCourseSearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StudentCourseSearchRequest.Merge(m, src)
}
func (m *StudentCourseSearchRequest) XXX_Size() int {
	return xxx_messageInfo_StudentCourseSearchRequest.Size(m)
}
func (m *StudentCourseSearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StudentCourseSearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StudentCourseSearchRequest proto.InternalMessageInfo

func (m *StudentCourseSearchRequest) GetStudentName() string {
	if m != nil {
		return m.StudentName
	}
	return ""
}

func (m *StudentCourseSearchRequest) GetCourseName() string {
	if m != nil {
		return m.CourseName
	}
	return ""
}

type StudentCourseSearchReply struct {
	StudentName          string   `protobuf:"bytes,1,opt,name=studentName,proto3" json:"studentName,omitempty"`
	CourseName           string   `protobuf:"bytes,2,opt,name=courseName,proto3" json:"courseName,omitempty"`
	ProfessorName        string   `protobuf:"bytes,3,opt,name=professorName,proto3" json:"professorName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StudentCourseSearchReply) Reset()         { *m = StudentCourseSearchReply{} }
func (m *StudentCourseSearchReply) String() string { return proto.CompactTextString(m) }
func (*StudentCourseSearchReply) ProtoMessage()    {}
func (*StudentCourseSearchReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec74e253189a04b7, []int{11}
}

func (m *StudentCourseSearchReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StudentCourseSearchReply.Unmarshal(m, b)
}
func (m *StudentCourseSearchReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StudentCourseSearchReply.Marshal(b, m, deterministic)
}
func (m *StudentCourseSearchReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StudentCourseSearchReply.Merge(m, src)
}
func (m *StudentCourseSearchReply) XXX_Size() int {
	return xxx_messageInfo_StudentCourseSearchReply.Size(m)
}
func (m *StudentCourseSearchReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StudentCourseSearchReply.DiscardUnknown(m)
}

var xxx_messageInfo_StudentCourseSearchReply proto.InternalMessageInfo

func (m *StudentCourseSearchReply) GetStudentName() string {
	if m != nil {
		return m.StudentName
	}
	return ""
}

func (m *StudentCourseSearchReply) GetCourseName() string {
	if m != nil {
		return m.CourseName
	}
	return ""
}

func (m *StudentCourseSearchReply) GetProfessorName() string {
	if m != nil {
		return m.ProfessorName
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "helloworld.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "helloworld.HelloReply")
	proto.RegisterType((*ProfessorRequest)(nil), "helloworld.ProfessorRequest")
	proto.RegisterType((*ProfessorReply)(nil), "helloworld.ProfessorReply")
	proto.RegisterType((*CourseRequest)(nil), "helloworld.CourseRequest")
	proto.RegisterType((*CourseReply)(nil), "helloworld.CourseReply")
	proto.RegisterType((*StudentRequest)(nil), "helloworld.StudentRequest")
	proto.RegisterType((*StudentReply)(nil), "helloworld.StudentReply")
	proto.RegisterType((*StudentCourseRequest)(nil), "helloworld.StudentCourseRequest")
	proto.RegisterType((*StudentCourseReply)(nil), "helloworld.StudentCourseReply")
	proto.RegisterType((*StudentCourseSearchRequest)(nil), "helloworld.StudentCourseSearchRequest")
	proto.RegisterType((*StudentCourseSearchReply)(nil), "helloworld.StudentCourseSearchReply")
}

func init() {
	proto.RegisterFile("helloworld/helloworld/helloworld.proto", fileDescriptor_ec74e253189a04b7)
}

var fileDescriptor_ec74e253189a04b7 = []byte{
	// 504 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x95, 0xdf, 0x8b, 0xd3, 0x40,
	0x10, 0xc7, 0x6d, 0x3d, 0x3c, 0x9d, 0x6b, 0x7b, 0xc7, 0x2a, 0x1a, 0xa3, 0x1c, 0x25, 0x1c, 0xc5,
	0x97, 0x26, 0x78, 0xe7, 0xb3, 0xe0, 0x55, 0xa8, 0x20, 0x1e, 0xe5, 0xfa, 0x20, 0xfa, 0x20, 0x6c,
	0x93, 0x31, 0x8d, 0x24, 0xd9, 0xb8, 0xbb, 0x41, 0x03, 0xea, 0x83, 0xff, 0x8e, 0xff, 0xa4, 0x64,
	0x37, 0xe9, 0x65, 0x4b, 0x5a, 0x7f, 0xd2, 0xb7, 0xdd, 0xd9, 0xf9, 0x7e, 0xbe, 0x93, 0x49, 0x26,
	0x0b, 0xa3, 0x25, 0xc6, 0x31, 0xfb, 0xc4, 0x78, 0x1c, 0x78, 0xad, 0x4b, 0x37, 0xe3, 0x4c, 0x32,
	0x02, 0x57, 0x11, 0xc7, 0x81, 0xde, 0x8b, 0x72, 0x77, 0x89, 0x1f, 0x73, 0x14, 0x92, 0x10, 0xd8,
	0x4b, 0x69, 0x82, 0x56, 0x67, 0xd8, 0x79, 0x74, 0xeb, 0x52, 0xad, 0x9d, 0x11, 0x40, 0x95, 0x93,
	0xc5, 0x05, 0xb1, 0x60, 0x3f, 0x41, 0x21, 0x68, 0x58, 0x27, 0xd5, 0x5b, 0x67, 0x06, 0x47, 0x33,
	0xce, 0xde, 0xa3, 0x10, 0x8c, 0x6f, 0xe1, 0x95, 0x04, 0x91, 0x2f, 0x3e, 0xa0, 0x2f, 0xad, 0xae,
	0x26, 0x54, 0x5b, 0x32, 0x80, 0x6e, 0x14, 0x58, 0xd7, 0x55, 0xb0, 0x1b, 0x05, 0xce, 0x05, 0x0c,
	0x1a, 0xc4, 0xd2, 0xfd, 0xdf, 0x78, 0x67, 0xd0, 0x9f, 0xb0, 0x9c, 0x0b, 0xdc, 0x56, 0x9e, 0x16,
	0x75, 0x57, 0xa2, 0xc7, 0x70, 0x50, 0x8b, 0x36, 0x55, 0xb0, 0x2e, 0x79, 0x02, 0x83, 0xb9, 0xcc,
	0x03, 0x4c, 0xe5, 0x9f, 0x18, 0x9d, 0x42, 0x6f, 0xa5, 0xfa, 0x5d, 0xa7, 0x6f, 0x70, 0xa7, 0xd2,
	0x98, 0x0f, 0x36, 0x84, 0x03, 0xa1, 0xe3, 0x17, 0x57, 0x88, 0x66, 0x88, 0x1c, 0x03, 0xf8, 0x4a,
	0xa2, 0x12, 0x34, 0xb1, 0x11, 0x21, 0x27, 0xd0, 0xcf, 0xea, 0xde, 0xab, 0x14, 0xdd, 0x46, 0x33,
	0xe8, 0x7c, 0x01, 0xb2, 0xe6, 0x5f, 0x56, 0xbe, 0x2b, 0xf7, 0x77, 0x60, 0x1b, 0xee, 0x73, 0xa4,
	0xdc, 0x5f, 0xfe, 0xb7, 0x1e, 0x38, 0xdf, 0x3b, 0x60, 0xb5, 0x1a, 0xec, 0xf0, 0x21, 0x4f, 0x7f,
	0xec, 0xc1, 0xfe, 0x94, 0x23, 0x4a, 0xe4, 0xe4, 0x29, 0xdc, 0x9c, 0xd3, 0x42, 0x4d, 0x23, 0xb1,
	0xdc, 0xc6, 0x64, 0x37, 0x87, 0xd8, 0xbe, 0xdb, 0x72, 0x92, 0xc5, 0x85, 0x73, 0x8d, 0x4c, 0xa0,
	0x5f, 0xeb, 0x9f, 0x85, 0x34, 0x4a, 0xff, 0x0a, 0xf2, 0x0a, 0x0e, 0x27, 0x1c, 0xa9, 0xc4, 0xd5,
	0x6c, 0x92, 0x87, 0xcd, 0xe4, 0xf5, 0x9f, 0x80, 0x6d, 0x6f, 0x38, 0xd5, 0xb8, 0xe7, 0xd0, 0xd3,
	0x38, 0xdd, 0x62, 0x72, 0xbf, 0x99, 0x6d, 0x7c, 0xd5, 0xf6, 0xbd, 0xb6, 0x23, 0x4d, 0x99, 0x42,
	0x5f, 0x53, 0xaa, 0xf7, 0x45, 0x0c, 0x53, 0x73, 0x1a, 0x6d, 0xab, 0xf5, 0x4c, 0x83, 0xde, 0xc0,
	0x6d, 0x03, 0x54, 0x55, 0x35, 0x6c, 0x91, 0x98, 0xc5, 0x1d, 0x6f, 0xc9, 0xd0, 0xe8, 0x05, 0x1c,
	0x4d, 0x51, 0x9a, 0xdc, 0xd1, 0x46, 0x95, 0xf1, 0x31, 0xdb, 0x27, 0xbf, 0xcc, 0x53, 0x1e, 0xe7,
	0x5f, 0xe1, 0x41, 0xc4, 0xdc, 0x90, 0x67, 0xbe, 0x8b, 0x9f, 0x69, 0x92, 0xc5, 0x28, 0x1a, 0xca,
	0xf3, 0x43, 0xf5, 0x26, 0x5f, 0x97, 0xeb, 0x59, 0x79, 0x19, 0xcc, 0x3a, 0x6f, 0x5f, 0x86, 0x91,
	0x5c, 0xe6, 0x0b, 0xd7, 0x67, 0x89, 0x47, 0x83, 0x48, 0x16, 0x74, 0x2c, 0xd1, 0x5f, 0x8e, 0x7d,
	0x96, 0x8a, 0x3c, 0x96, 0x51, 0x1a, 0x7a, 0x21, 0x1b, 0x97, 0x44, 0x4f, 0x72, 0x44, 0x2f, 0xa1,
	0x42, 0x22, 0x6f, 0xbf, 0x61, 0x16, 0x37, 0xd4, 0x15, 0x73, 0xf6, 0x33, 0x00, 0x00, 0xff, 0xff,
	0x68, 0x1b, 0xba, 0x68, 0x8c, 0x06, 0x00, 0x00,
}
